# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end

target 'LiangPiao' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LianPiao
    pod 'Alamofire', '~> 3.5.0'
    pod 'SnapKit','~> 0.22.0'
    pod 'SDWebImage', '~> 4.0.0-beta2'
    pod 'MBProgressHUD'
    pod 'FDFullscreenPopGesture', '1.1'
    pod 'DZNEmptyDataSet'
    pod 'ReactiveCocoa','~> 4.2.2'
#    pod 'Fabric'
#    pod 'Crashlytics'
    pod 'MJRefresh'
    pod 'MJExtension'
    pod 'AMapLocation' #定位SDK
    pod 'IQKeyboardManagerSwift', '4.0.5'
end


